[package]
name = "mybip39"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-bip39 = "2.0.0"
bitcoin = "0.32.4"
secp256k1 = "0.29.1"